version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "12:00"
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: concurrently
    versions:
    - 5.3.0
    - 6.0.0
    - 6.0.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: react-redux
    versions:
    - 7.2.2
    - 7.2.3
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.10
    - 7.12.13
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
